# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm9zyOhM237M-_snXROls5J4c8Ztdjdx
"""

nota1 = float(input("insira a primeira nota: "))
nota2 = float(input("insira a segunda nota: "))

media = (nota1 + nota2)/2

if media >= 6:
  print("aprovado")
else:
  print("reprovado")